### ISSUE TITLE
AssertionError in PoseGenerator

### ISSUE THREAD

**Issue by nies14** [Graformer/GraFormer#1]
Thanks for the great work.

Getting AssertionError in PoseGenerator class while training

Full stacktrace:
"==> Using settings Namespace(dataset='h36m', keypoints='cpn_ft_h36m_dbb', actions='*', evaluate='', resume='', checkpoint='checkpoint', snapshot=5, n_head=4, dim_model=96, n_layer=5, dropout=0.25, batch_size=64, epochs=100, num_workers=1, lr=0.001, lr_decay=50000, lr_gamma=0.9, downsample=1, max_norm=True)
==> Loading dataset...
==> Preparing data...
==> Loading 2D detections...
==> Creating model...
==> Total parameters: 0.65M
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/graformer/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/anaconda3/envs/graformer/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/user/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/user/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/user/anaconda3/envs/graformer/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/user/anaconda3/envs/graformer/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/user/anaconda3/envs/graformer/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/Desktop/Research/PoseFormer-main/Post-Work/GraFormer/main_GraFormer.py", line 294, in <module>
    main(parse_args())
  File "/home/user/Desktop/Research/PoseFormer-main/Post-Work/GraFormer/main_GraFormer.py", line 170, in main
    train_loader = DataLoader(PoseGenerator(poses_train, poses_train_2d, actions_train), batch_size=args.batch_size,
  File "/home/user/Desktop/Research/PoseFormer-main/Post-Work/GraFormer/common/generators.py", line 17, in __init__
    assert self._poses_3d.shape[0] == self._poses_2d.shape[0] and self._poses_3d.shape[0] == len(self._actions)
AssertionError"

**Comment by nies14** [comment]
Solved. I was using wrong keypoints.

**Comment by wangdazhong258** [comment]
> 解决了。我使用了错误的关键点。

Can you tell me how to solve it
